server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: JustAI-test
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      database: 0
vk:
  api:
    version: ${VK_API_VERSION:5.199}
    access_token: ${VK_API_ACCESS_TOKEN:vk1.a.fu1oA5serBcGYhEdsBzlU_j0CM-fQ2R3f6oSQy35IzmmYZ9TAOd2DEo5jBjGqOF6ENzDvzO09VwXs0Ii47q7KmqEfYp522VRtRWld6PQEBHw_gzsrNrJ5oGHFkSh5S-uEdpb-x8HAh0Q4An-5zrmq4cBJyryKUUTSEW0QFKso91lESvTuxQdke4tkYmoHgyCVQo1xI1mZMFVn1Oy8vS5OA}
    confirmation_key: bf4d3a72